### ISSUE TITLE
FreeBSD and OpenBSD VMs don't start - error running `sudo` during initialisation.

### ISSUE THREAD

**Issue by DrHyde** [cross-platform-actions/action#88]
I have [two](https://github.com/DrHyde/perl-modules-Number-Phone/actions/runs/9420864630/job/25954385778) [workflows](https://github.com/DrHyde/perl-modules-Number-Phone/actions/runs/9420864618/job/25954253658) which fail consistently while FreeBSD and OpenBSD VMs are starting, both with the messages:

```
Initializing VM
Error: The process '/usr/bin/sudo' failed with exit code null
```

My OpenBSD action doesn't use sudo at all. The FreeBSD one does, to install some software in the VM, but isn't getting that far.

**Comment by jacob-carlborg** [comment]
Strange, I'll take a look. `sudo` is used by the action before the VM starts.

**Comment by jacob-carlborg** [comment]
@DrHyde could you please set the following variables to `true` and rerun the job: `ACTIONS_RUNNER_DEBUG` and `ACTIONS_STEP_DEBUG `?

**Comment by DrHyde** [comment]
Done, but I don't see any extra debug - did I put the variables in the right place?

Here's the [FreeBSD build](https://github.com/DrHyde/perl-modules-Number-Phone/actions/runs/9505865257/job/26202031054) and the [OpenBSD build](https://github.com/DrHyde/perl-modules-Number-Phone/actions/runs/9505865254/job/26202122362).

**Comment by jacob-carlborg** [comment]
> Done, but I don't see any extra debug - did I put the variables in the right place?

Probably not. I usually put them as a secret variable in Settings -> Security -> Secrets and variables -> Actions -> Secrets.

**Comment by DrHyde** [comment]
Ahh that's better, lots of extra debug: [FreeBSD](https://github.com/DrHyde/perl-modules-Number-Phone/actions/runs/9514214767/job/26226390953) [OpenBSD](https://github.com/DrHyde/perl-modules-Number-Phone/actions/runs/9514214769/job/26226048107)

**Comment by jacob-carlborg** [comment]
Ok, I can see the error now. The problem is that you're using `macos-latest` as the runner [1]. That was recently updated to correspond to macos-14, which is Apple Silicon only. The Xhyve hypervisor, that is used by default for FreeBSD and OpenBSD, is not compatible with Apple Silicon. I recommend switching to `ubuntu-latest` instead, then it will use the QEMU hypervisor. GitHub fairly recently added support for hardware accelerated nested virtualization on the Ubuntu runners. They  also have better performance compared to the macOS runners now. The QEMU hypervisor is also more stable than the Xhyve hypervisor.

It's the same error for both the FreeBSD and OpenBSD jobs.

[1] https://github.com/DrHyde/perl-modules-Number-Phone/blob/ff6ad7c69c9aa41ddedc7de0644d2e688f7c3bc4/.github/workflows/freebsd.yml#L6

**Comment by DrHyde** [comment]
Yep, that fixed it. Thanks!
